# flake8: noqa

#_._encode_json_uid  # unused method (git_anon/anon_config.py:88)
cls  # unused variable (git_anon/anon_identity.py:17)
_._signatures  # unused attribute (git_anon/api_functions.py:107)
_._signatures  # unused attribute (git_anon/gpg_general/key_utils.py:12)
_._children  # unused attribute (git_anon/gpg_general/key_utils.py:22)
#_.strip_signatures_uids_subkeys  # unused method (git_anon/gpg_general/key_utils.py:24)
#_.set_expended  # unused method (git_anon/keystores/gpg_keystore_personal.py:57)
#_.halg  # unused attribute (git_anon/library_patches/patched_pgpy_functions.py:133)
#_.halg  # unused attribute (git_anon/library_patches/patched_pgpy_functions.py:135)
new_identity  # unused function (git_anon_cli/__init__.py:70)
update_mappings  # unused function (git_anon_cli/__init__.py:153)
list_userids  # unused function (git_anon_cli/__init__.py:183)
cert_sign  # unused function (git_anon_cli/__init__.py:209)
cert_import  # unused function (git_anon_cli/__init__.py:237)
cert_trust  # unused function (git_anon_cli/__init__.py:244)
throw  # unused function (git_anon_cli/__init__.py:296)
environment  # unused function (git_anon_cli/__init__.py:301)
pull  # unused function (git_anon_cli/__init__.py:311)
push  # unused function (git_anon_cli/__init__.py:316)